name: Build and Deploy to cloud
on:
  push:
    branches:
      - main

jobs:
  builtAndDeploy:
  
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Built and Deploy with Maven
        env:
         CONNECTED_APP_CLIENT_ID: "${{ secrets.CONNECTED_APP_CLIENT_ID }}"

      - name: Check Values
        run: echo "CONNECTED_APP_ID is :" "${env.CONNECTED_APP_CLIENT_ID}"
          
      # - name: Deploy to Exchange
      #   run: mvn deploy --settings settings.xml
        
      # - name: Deploy to Cloudhub 
      #   run: mvn deploy -DmuleDeploy -Den="${{vars.EN}}" -Dsecure_key="${{secrets.SECURE_KEY}}" --settings settings.xml 


