name: Build and Deploy to cloud
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        distribution: 'us-east-1'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        
    - name: Determine Environment Name
      id: extract_env_name
      run: echo "::set-output name=environment::${GITHUB_REF#refs/heads/}"  # Extracts branch name without 'refs/heads/'
      
    - name: Print Environment Dynamically
      run: echo "-Denvironment=" "${{ steps.extract_env_name.outputs.environment }}"

    - name: Determine Environment Name
      id: extract_env
      run: echo "::set-output name=environment::${GITHUB_REF#refs/heads/}"  # Extracts branch name without 'refs/heads/'
      
    - name: Print Environment Dynamically
      run: |
        echo "-Denvironment=${{ steps.extract_env.outputs.environment }}"
    # - name: Deploy to Exchange
    #   run: mvn deploy --settings .maven/settings.xml
        
    # - name: Deploy to Cloudhub 
    #   run: mvn deploy -DmuleDeploy 
    #       -Den="${{vars.EN}}" 
    #       -Denvironment="${{vars.EN}}" 
    #       -Dsecure_key="${{secrets.SECURE_KEY}}" 
    #       -Dorg_id="${{secrets.ORG_ID}}" 
    #       -Dconnected_app_client_id="${{secrets.CONNECTED_APP_CLIENT_ID}}" 
    #       -Dconnected_app_secret="${{secrets.CONNECTED_APP_CLIENT_SECRET}}" --settings .maven/settings.xml 


