name: Build and Deploy to cloud
on:
  push:
    branches:
      - main
      - dev
      - qa
      - uat

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        distribution: 'us-east-1'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Deploy to Cloudhub
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
        ENVIRONMENT="dev"
        elif [[ ${{ github.ref }} == 'refs/heads/qa' ]]; then
        ENVIRONMENT="qa"
        elif [[ ${{ github.ref }} == 'refs/heads/uat' ]]; then
          ENVIRONMENT="uat"
        else
          echo "Unsupported branch for deployment"
          exit 1
        fi

        echo "Deploying to environment: $ENVIRONMENT"
      
    # - name: Deploy to Exchange
    #   run: mvn deploy --settings .maven/settings.xml
        
    # - name: Deploy to Cloudhub 
    #   run: mvn deploy -DmuleDeploy 
    #       -Den="${{vars.EN}}" 
    #       -Denvironment="${{vars.EN}}" 
    #       -Dsecure_key="${{secrets.SECURE_KEY}}" 
    #       -Dorg_id="${{secrets.ORG_ID}}" 
    #       -Dconnected_app_client_id="${{secrets.CONNECTED_APP_CLIENT_ID}}" 
    #       -Dconnected_app_secret="${{secrets.CONNECTED_APP_CLIENT_SECRET}}" --settings .maven/settings.xml 


